
name = "Product Badge"
type = "theme"

[settings]
[[settings.blocks]]
type = "product_badge"
name = "Product Badge"
target = "section_group://product-information"

[[settings.blocks.settings]]
type = "checkbox"
id = "show_badge"
label = "Show Product Badge"
default = true

[[settings.blocks.settings]]
type = "select"
id = "badge_position"
label = "Badge Position"
default = "top-left"
options = [
  { value = "top-left", label = "Top Left" },
  { value = "top-right", label = "Top Right" },
  { value = "bottom-left", label = "Bottom Left" },
  { value = "bottom-right", label = "Bottom Right" }
]